---
- name: INVALID is DROP
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: INVALID
    jump: DROP
  become: yes

- name: Allow ESTABLISHED,RELATED
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name:  localhost
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: Enable Loopback
  become: yes


- name: Allow TCP port 22 (SSH) from My IP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
    source: '{{ item }}'
  with_items:
    - "{{ my_ip }}"

- name: policy INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Save IPtables
  ansible.builtin.shell:
    cmd: service netfilter-persistent save
    chdir: /usr/sbin/

